project:
  type: website

website:
  title: "ELDANALYZE"
  navbar:
    left:
      - href: "ProjectOverview/ProjectOverview.html"
        text: "Project Overview"
      - href: "ShinyApp/UserGuide.html"
        text: "User Guide"
    right:
      - href: "ShinyApp/UserGuide.html"
        text: "ShinyApp"
      
     

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

