---
title: "IS415 Project"
---

# [Abstract]{.underline}

Singapore is experiencing an ageing population, with an increasing proportion of the citizens aged 65 and older by 11.7% compared to 10 years ago ([Source](https://www.cnbc.com/2023/10/30/as-singapores-aging-population-grows-businesses-court-older-spenders.html)). In addition, the life expectancy of Singaporeans has been steadily rising over the past five decades ([Source](https://smartwealth.sg/life-expectancy/)). This has prompted the government to commit to building more eldercare facilities nationwide. Alongside this has come a push for Active Ageing to encourage the elderly to “stay active, healthy and socially engaged”. ([Source](https://www.moh.gov.sg/ifeelyoungsg/how-can-i-age-actively/stay-healthy/active-ageing-programmes)) To achieve this goal, the government has also been trying to increase the number of active ageing centres ([Source](https://www.straitstimes.com/singapore/politics/ndr-2023-active-ageing-centres-to-be-expanded-to-help-seniors-stay-active-and-healthy)) and possible locations for activities to make it more accessible to seniors.

Our project would like to understand what the current distribution of eldercare facilities and amenities is across Singapore and selected planning areas within Singapore. We want to investigate whether there are enough facilities and amenities to ensure that the elderly not just age healthily, but age well. We also want to understand whether there are any clusters of the elderly population, and whether the distribution of facilities and amenities creates an overlapping cluster.

Our objectives are first to obtain and visualise the hot and cold spots of the elderly population across Singapore as well as all eldercare facilities and amenities. We want to investigate whether eldercare facilities are spread evenly or overlap in clusters with clusters of elderly population.
